export const LOGIN = "LOGIN"
export const LOGIN_SUCCES = "LOGIN_SUCCES"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED"

export const DELETE_PRODUCTS = "DELETE_PRODUCTS"
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS"
export const DELETE_PRODUCTS_FAILED = "DELETE_PRODUCTS_FAILED"

export const EDIT_PRODUCTS = "EDIT_PRODUCTS"
export const EDIT_PRODUCTS_SUCCESS = "EDIT_PRODUCTS_SUCCESS"
export const EDIT_PRODUCTS_FAILED = "EDIT_PRODUCTS_FAILED"

export const ADD_PRODUCTS = "ADD_PRODUCTS"
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS"
export const ADD_PRODUCTS_FAILED = "ADD_PRODUCTS_FAILED"

export const ADD_COUNT_CARD = "ADD_COUNT_CARD"

export const ADD_CARD = "ADD_CARD"
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS"
export const ADD_CARD_FAILED = "ADD_CARD_FAILED"

export const GET_CARD = "GET_CARD"
export const GET_CARD_SUCCESS = "GET_CARD_SUCCESS"
export const GET_CARD_FAILED = "GET_CARD_FAILED"

